"""added ai response and slatracker

Revision ID: 19060ce3d034
Revises: f33ef47c3a59
Create Date: 2026-01-03 11:45:38.318646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19060ce3d034'
down_revision: Union[str, Sequence[str], None] = 'f33ef47c3a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('draft_response', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('was_approved', sa.Boolean(), nullable=True),
    sa.Column('edited_by_agent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sla_trackers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('first_response_deadline', sa.DateTime(), nullable=True),
    sa.Column('resolution_deadline', sa.DateTime(), nullable=True),
    sa.Column('breached', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ticket_messages', sa.Column('sender_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_messages', 'sender_id')
    op.drop_table('sla_trackers')
    op.drop_table('ai_responses')
    # ### end Alembic commands ###
