"""added supabase user id in users

Revision ID: 7ad3614967d8
Revises: 19060ce3d034
Create Date: 2026-01-05 21:55:08.219891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ad3614967d8'
down_revision: Union[str, Sequence[str], None] = '19060ce3d034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('supabase_user_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['supabase_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'supabase_user_id')
    # ### end Alembic commands ###
