"""create core tables

Revision ID: f33ef47c3a59
Revises: ef32e82c60e9
Create Date: 2026-01-03 01:50:40.946747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f33ef47c3a59'
down_revision: Union[str, Sequence[str], None] = 'ef32e82c60e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tickets', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('tickets', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('category', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('sentiment', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('ai_confidence', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('assigned_agent_id', sa.UUID(), nullable=True))
    op.add_column('tickets', sa.Column('is_auto_resolved', sa.Boolean(), nullable=True))
    op.alter_column('tickets', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tickets', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'tickets', 'users', ['assigned_agent_id'], ['id'])
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.alter_column('tickets', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tickets', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('tickets', 'is_auto_resolved')
    op.drop_column('tickets', 'assigned_agent_id')
    op.drop_column('tickets', 'ai_confidence')
    op.drop_column('tickets', 'sentiment')
    op.drop_column('tickets', 'category')
    op.drop_column('tickets', 'priority')
    op.drop_column('tickets', 'description')
    op.drop_table('ticket_messages')
    # ### end Alembic commands ###
